//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizeProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soru
    {
        public int soruId { get; set; }
        public string soru1 { get; set; }
        public int cevap { get; set; }
        public int kategori { get; set; }
        public int yazar { get; set; }
    
        public virtual Cevap Cevap1 { get; set; }
        public virtual Kategori Kategori1 { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
